language: python

python:
    - 2.7

cache:
    apt: true

before_install:
    - pip install -U pip flake8
    - flake8 lymph
    - sudo apt-get update -qq
    - sudo apt-get install zookeeper

install:
    - pip install
      $(if [ $MAJOR_TRAVIS_PYTHON_VERSION = "3" ]; then echo "-r requirements/base.txt"; fi)
      -r requirements/dev.txt
      -r requirements/docs.txt

before_script:
    - export ZOOKEEPER_PATH=/usr/share/java

script:
    - nosetests

notifications:
    email:
        on_success: never
        on_failure: always
